---
title: "106-neighbor-net"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Phylogenetic Network
A low-hanging fruit may be to try a distance-based network analysis of the data. 

## Neighbor Net in Phangorn

```{r nn, warning=FALSE, message=FALSE}
library(phangorn)
data(yeast)
dm <- dist.ml(yeast)
nnet <- neighborNet(dm)
plot(nnet, "2D")
```

Let's try that for our data
```{r nn2, warning=FALSE, message=FALSE}
phylip<-read.phyDat(file="outputs/100/test.asc.phy")
dm <- dist.ml(phylip)
nnet <- neighborNet(dm)
plot(nnet, "2D")

nj <- NJ(dm)
plot(nj)
```

Ok, I don't know how to interpret that.

### Test3

```{r test3, warning=FALSE, message=FALSE}
phylip<-read.phyDat(file="outputs/100/test3.asc.phy")
dm <- dist.ml(phylip)
nnet <- neighborNet(dm)
plot(nnet, "2D")

nj<-NJ(dm)
plot(nj)
```

Just the omy05 bit.   
```{r omy05, warning=FALSE, message=FALSE}
omy05<-read.phyDat(file="outputs/100/test3-omy05.asc.phy")
dm <- dist.ml(omy05)
nnet <- neighborNet(dm)
plot(nnet, "2D")
```

### Test4
Compute nnet & NJ.  
```{r test4, warning=FALSE, message=FALSE}
phylip<-read.phyDat(file="outputs/100/test4-maf05p.asc.phy")
dm <- dist.ml(phylip)
nj<-NJ(dm)
nnet <- neighborNet(dm)
plot(nnet, "2D")
#write.nexus(nnet, file="outputs/100/test4-maf05.asc.nnet.tre")
```

Plot NJ more nicely   
```{r ggtree, warning=FALSE, message=FALSE}
library(ggtree)

tree <- ape::root(nj, c("PCT_PPP1_01\t","LCT_GACR_10\t"))
ggtree(tree)+geom_tiplab(size=2)
```

### Test4 omy05
```{r omy05-4, warning=FALSE, message=FALSE}
omy05<-read.phyDat(file="outputs/100/test4-maf05p-omy05.asc.phy")
dm <- dist.ml(omy05)
nnet <- neighborNet(dm)
plot(nnet, "2D")
```

### Test5
Compute NJ.  
```{r test5, warning=FALSE, message=FALSE}
phylip<-read.phyDat(file="outputs/100/test5p.asc.phy")
subset<-subset(phylip, 1:18)

phylip05<-read.phyDat(file="outputs/100/test5-maf05p.asc.phy")
subset05<-subset(phylip05, 1:18)


phylip10<-read.phyDat(file="outputs/100/test5-maf10p.asc.phy")
subset10<-subset(phylip10, 1:18)


dm <- dist.ml(subset)
nj<-NJ(dm)

dm05 <- dist.ml(subset05)
nj05<-NJ(dm05)

dm10<-dist.ml(subset10)
nj10<-NJ(dm10)
```

Plot NJ more nicely   
```{r ggtree05, warning=FALSE, message=FALSE}
library(ggtree)

#tree <- ape::root(nj, c("PCT_PPP1_01\t","LCT_GACR_10\t"))
ggtree(nj)+geom_tiplab(size=2)
ggtree(nj05)+geom_tiplab(size=2)
ggtree(nj10)+geom_tiplab(size=2)
```

Don't forget about the network....
```{r network5, warning=FALSE, message=FALSE}
nnet <- neighborNet(dist.ml(subset))
plot(nnet, "2D")

nnet05 <- neighborNet(dist.ml(subset05))
plot(nnet05, "2D")

nnet10<-neighborNet(dist.ml(subset10))
plot(nnet10, "2D")
```