---
title: "904-explicit-network"
author: "Mac Campbell"
date: "2022-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
```

## 

```{r, warning=FALSE, message=FALSE}
source("~/github/SNPs2CF/functions.R")
```

```{r, warning=FALSE, message=FALE, eval=FALSE}
output <- SNPs2CF(seqMatrix="outputs/900/test14-maf05p-sites.sort.prune.reheadered.min4.phy",
                  ImapName="outputs/904/test14-imap.txt", between.sp.only = TRUE, max.SNPs = NULL,
                  bootstrap=FALSE, outputName="outputs/904/allq-AllSNP-btsp.csv",
                  save.progress=FALSE,
                  cores = 3);
```

#Credibility Intervals
To bootstrap I need to put together CF's with CIs

```{r, warning=FALSE, message=FALE, eval=FALSE}
ciout <- SNPs2CF(seqMatrix="outputs/900/test14-maf05p-sites.sort.prune.reheadered.min4.phy",
                  ImapName="outputs/904/test14-imap.txt", between.sp.only = TRUE, max.SNPs = NULL,
                  bootstrap=TRUE, boots.rep=1000,
                  outputName="outputs/904/allq-AllSNP-btsp-CI.csv",
                  save.progress=FALSE,
                  cores = 3);
```